### ISSUE TITLE
Bias must be a finite number, got NaN

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#210]
6 mutations, mutation rate 50.0%, elitism 1, mutation ALL, selection POWER, timeout 4, PopSize 50 SAMPLER
Training 525d7d0a scheduled
error: Uncaught (in worker "worker-1") (in promise) Error: Bias must be a finite number, got NaN
    throw new Error(`Bias must be a finite number, got ${targetBias}`);
          ^
    at limitBias (https://deno.land/x/neat_ai@v0.10.5/src/architecture/BackPropagation.ts:212:11)
    at adjustedBias (https://deno.land/x/neat_ai@v0.10.5/src/architecture/BackPropagation.ts:120:16)
    at IF.propagate (https://deno.land/x/neat_ai@v0.10.5/src/methods/activations/aggregate/IF.ts:388:19)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:362:71)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:420:55)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:420:55)
    at Creature.propagate (https://deno.land/x/neat_ai@v0.10.5/src/Creature.ts:947:9)
    at trainDir (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Training.ts:180:17)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async WorkerProcessor.process (https://deno.land/x/neat_ai@v0.10.5/src/multithreading/workers/WorkerProcessor.ts:69:22)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:167:19)
    at eventLoopTick (ext:core/01_core.js:182:7)

**Comment by nleck** [comment]
error: Uncaught (in worker "worker-4") (in promise) Error: Bias must be a finite number, got NaN
    throw new Error(`Bias must be a finite number, got ${targetBias}`);
          ^
    at limitBias (https://deno.land/x/neat_ai@v0.10.5/src/architecture/BackPropagation.ts:212:11)
    at adjustedBias (https://deno.land/x/neat_ai@v0.10.5/src/architecture/BackPropagation.ts:120:16)
    at IF.propagate (https://deno.land/x/neat_ai@v0.10.5/src/methods/activations/aggregate/IF.ts:388:19)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:362:71)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:420:55)
    at Node.propagate (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Node.ts:420:55)
    at Creature.propagate (https://deno.land/x/neat_ai@v0.10.5/src/Creature.ts:947:9)
    at trainDir (https://deno.land/x/neat_ai@v0.10.5/src/architecture/Training.ts:180:17)
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async WorkerProcessor.process (https://deno.land/x/neat_ai@v0.10.5/src/multithreading/workers/WorkerProcessor.ts:69:22)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:167:19)
    at eventLoopTick (ext:core/01_core.js:182:7)
Cloning into 'GRQ-logs'...
