### ISSUE TITLE
Error: to: 644 should not be less than from: 666

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#293]
error: Uncaught (in worker "worker-2") (in promise) Error: to: 644 should not be less than from: 666
      throw new Error("to: " + to + " should not be less than from: " + from);
            ^
    at Creature.connect (https://deno.land/x/neat_ai@v0.25.0/src/Creature.ts:800:13)
    at removeNeuron (https://deno.land/x/neat_ai@v0.25.0/src/compact/CompactUnused.ts:95:18)
    at compactUnused (https://deno.land/x/neat_ai@v0.25.0/src/compact/CompactUnused.ts:28:11)
    at trainDir (https://deno.land/x/neat_ai@v0.25.0/src/architecture/Training.ts:260:27)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async WorkerProcessor.process (https://deno.land/x/neat_ai@v0.25.0/src/multithreading/workers/WorkerProcessor.ts:69:22)
    at async workerHandler.onmessage (https://deno.land/x/neat_ai@v0.25.0/src/multithreading/workers/deno/worker.ts:10:18)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:167:19)
    at eventLoopTick (ext:core/01_core.js:153:7)

**Comment by nleck** [comment]
error: Uncaught (in worker "worker-2") (in promise) Error: to: 649 should not be less than from: 667
      throw new Error("to: " + to + " should not be less than from: " + from);
            ^
    at Creature.connect (https://deno.land/x/neat_ai@v0.25.0/src/Creature.ts:800:13)
    at removeNeuron (https://deno.land/x/neat_ai@v0.25.0/src/compact/CompactUnused.ts:95:18)
    at compactUnused (https://deno.land/x/neat_ai@v0.25.0/src/compact/CompactUnused.ts:28:11)
    at Creature.applyLearnings (https://deno.land/x/neat_ai@v0.25.0/src/Creature.ts:907:29)
    at trainDir (https://deno.land/x/neat_ai@v0.25.0/src/architecture/Training.ts:251:22)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async WorkerProcessor.process (https://deno.land/x/neat_ai@v0.25.0/src/multithreading/workers/WorkerProcessor.ts:69:22)
    at async workerHandler.onmessage (https://deno.land/x/neat_ai@v0.25.0/src/multithreading/workers/deno/worker.ts:10:18)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:167:19)
    at eventLoopTick (ext:core/01_core.js:153:7)
