### ISSUE TITLE
Activation value 0.9900000842251925 is outside the valid range [-0.99, 0.99]

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#454]
error: Uncaught (in worker "worker-259") (in promise) Error: SOFTSIGN: Activation value 0.9900000842251925 is outside the valid range [-0.99, 0.99]
      throw new Error(
            ^
    at SOFTSIGN.unSquash (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/methods/activations/types/SOFTSIGN.ts:26:13)
    at toValue (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/BackPropagation.ts:196:28)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:389:27)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.0/src/architecture/Neuron.ts:435:49)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
Cloning into 'GRQ-logs'...

**Comment by nleck** [comment]
error: Uncaught (in worker "worker-53") (in promise) Error: SOFTSIGN: Activation value 0.9900000572542154 is outside the valid range [-0.99, 0.99]
      throw new Error(
            ^
    at SOFTSIGN.unSquash (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/methods/activations/types/SOFTSIGN.ts:26:13)
    at toValue (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/BackPropagation.ts:186:28)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:389:27)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
    at Neuron.propagate (https://jsr.io/@stsoftware/neat-ai/0.102.2/src/architecture/Neuron.ts:435:49)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
