### ISSUE TITLE
Find Squash on a constant = ERROR

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#74]
iteration 2 score -0.589680493343595 error 0.5896625933435949 avg time [33m15,360 ms[39m
Rebooting fine tuning, elitist: 1
Trace
    at Function.find (file:///Users/nigel/src/NEAT-TS/src/methods/activations/Activations.ts:120:17)
    at Node.findSquash (file:///Users/nigel/src/NEAT-TS/src/architecture/Node.ts:89:44)
    at Node.applyLearnings (file:///Users/nigel/src/NEAT-TS/src/architecture/Node.ts:287:31)
    at Network.applyLearnings (file:///Users/nigel/src/NEAT-TS/src/architecture/Network.ts:881:21)
    at Network.trainDir (file:///Users/nigel/src/NEAT-TS/src/architecture/Network.ts:1312:14)
    at WorkerProcessor.process (file:///Users/nigel/src/NEAT-TS/src/multithreading/workers/WorkerProcessor.ts:65:30)
    at workerHandler.onmessage (file:///Users/nigel/src/NEAT-TS/src/multithreading/workers/deno/worker.ts:10:34)
    at wrappedHandler (ext:deno_web/02_event.js:1405:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:783:7)
    at invokeEventListeners (ext:deno_web/02_event.js:823:5)
[0m[1m[31merror[0m: Uncaught (in worker "") (in promise) "Unknown activation: UNDEFINED-constant-477"
[0m[1m[31merror[0m: Uncaught (in promise) Error: Unhandled error in child worker.
    at [0m[1m[3mWorker.#pollControl[0m ([0m[36mext:runtime/11_workers.js[0m:[0m[33m157[0m:[0m[33m19[0m)

**Comment by nleck** [comment]
Rebooting fine tuning, elitist: 2
Trace
    at Function.find (file:///home/nigel/src/NEAT-TS/src/methods/activations/Activations.ts:120:17)
    at Node.findSquash (file:///home/nigel/src/NEAT-TS/src/architecture/Node.ts:89:44)
    at Node.applyLearnings (file:///home/nigel/src/NEAT-TS/src/architecture/Node.ts:288:31)
    at Network.applyLearnings (file:///home/nigel/src/NEAT-TS/src/architecture/Network.ts:881:21)
    at Network.trainDir (file:///home/nigel/src/NEAT-TS/src/architecture/Network.ts:1312:14)
    at WorkerProcessor.process (file:///home/nigel/src/NEAT-TS/src/multithreading/workers/WorkerProcessor.ts:65:30)
    at workerHandler.onmessage (file:///home/nigel/src/NEAT-TS/src/multithreading/workers/deno/worker.ts:10:34)
    at wrappedHandler (ext:deno_web/02_event.js:1405:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:783:7)
    at invokeEventListeners (ext:deno_web/02_event.js:823:5)
[0m[1m[31merror[0m: Uncaught (in worker "") (in promise) "Unknown activation: UNDEFINED-constant-477"
[0m[1m[31merror[0m: Uncaught (in promise) Error: Unhandled error in child worker.
    at [0m[1m[3mWorker.#pollControl[0m ([0m[36mext:runtime/11_workers.js[0m:[0m[33m157[0m:[0m[33m19[0m)
