### ISSUE TITLE
DNA-sane fails.

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#93]
Trace
    at Network.connect (file:///Users/nigel/src2/NEAT-TS/src/architecture/Network.ts:763:15)
    at file:///Users/nigel/src2/NEAT-TS/src/architecture/Offspring.ts:184:19
    at Array.forEach (<anonymous>)
    at Function.bread (file:///Users/nigel/src2/NEAT-TS/src/architecture/Offspring.ts:182:20)
    at Neat.offspring (file:///Users/nigel/src2/NEAT-TS/src/Neat.ts:480:32)
    at Neat.evolve (file:///Users/nigel/src2/NEAT-TS/src/Neat.ts:291:31)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Network.evolveDir (file:///Users/nigel/src2/NEAT-TS/src/architecture/Network.ts:997:32)
    at async file:///Users/nigel/src2/GRQ/src/industry/EvolveApp.ts:245:20
error: Uncaught (in promise) "from should not be from an output node (667, len: 670, output: 3): 667"

**Comment by nleck** [comment]
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
          if (other.type === "output") {
                    ^
    at Function.bread (file:///Users/nigel/src2/NEAT-TS/src/architecture/Offspring.ts:67:21)
    at Neat.offspring (file:///Users/nigel/src2/NEAT-TS/src/Neat.ts:480:32)
    at Neat.evolve (file:///Users/nigel/src2/NEAT-TS/src/Neat.ts:291:31)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Network.evolveDir (file:///Users/nigel/src2/NEAT-TS/src/architecture/Network.ts:997:32)
    at async file:///Users/nigel/src2/GRQ/src/industry/EvolveApp.ts:245:20
