### ISSUE TITLE
from should be a non-negative integer was: NaN"

### ISSUE THREAD

**Issue by nleck** [stSoftwareAU/NEAT-TS#96]
Trace
    at Network.connect (file:///Users/nigel/src2/NEAT-TS/src/architecture/Network.ts:752:15)
    at file:///Users/nigel/src2/NEAT-TS/src/reconstruct/CRISPR.ts:106:18
    at Array.forEach (<anonymous>)
    at CRISPR.apply (file:///Users/nigel/src2/NEAT-TS/src/reconstruct/CRISPR.ts:96:21)
    at file:///Users/nigel/src2/GRQ/src/industry/EvolveApp.ts:171:33
error: Uncaught "from should be a non-negative integer was: NaN"

**Comment by nleck** [comment]
{
  weight: -0.5544230711140505,
  fromUUID: "input-1",
  toUUID: "c8bb7e54-0afd-46a4-b543-fcc00fda1b25"
}
Trace
    at Network.connect (file:///Users/nigel/src2/NEAT-TS/src/architecture/Network.ts:751:15)
    at file:///Users/nigel/src2/NEAT-TS/src/reconstruct/CRISPR.ts:111:18
    at Array.forEach (<anonymous>)
    at CRISPR.apply (file:///Users/nigel/src2/NEAT-TS/src/reconstruct/CRISPR.ts:101:21)
    at file:///Users/nigel/src2/GRQ/src/industry/EvolveApp.ts:170:33
error: Uncaught "from should be a non-negative integer was: NaN"
Starting Industry... Mon 19 Jun 2023 19:57:50 AEST
